### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by ranakhan** [jacksiro254/q2a-blog-post#16]
Hi I am trying to use this plugin for my website but getting this error;

![image](https://user-images.githubusercontent.com/10131997/85915030-f1dd7a00-b811-11ea-8519-1581d737bbcd.png)

Even when going into article page, further more broken links;

![image](https://user-images.githubusercontent.com/10131997/85915047-18031a00-b812-11ea-92f7-10e4fbe3694a.png)

This is my website:
[](http://www.kisanmashwara.com/qa/agriculture-information-blog)

Can you please help me to fix these issues? Thanks in advance!

Rana

**Comment by JacksiroKe** [comment]
thanks sir for highlighting this issue I will check and fix asap

**Comment by jacksiro254** [comment]
I believe this issue was fixed
